import type { Metadata } from "next";
import styles from '@/styles/layout.module.scss';
import '@/styles/base.scss';
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: 'lu.is',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className={styles.overall}>
          {children}
        </main>
      </body>
    </html>
  );
}
